package hbi.core.handchina.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "c_wer")
public class Wer extends BaseDTO {

     public static final String FIELD_CID = "cid";
     public static final String FIELD_CNAME = "cname";
     public static final String FIELD_CAGE = "cage";
     public static final String FIELD_CWEIGHT = "cweight";


     @Id
     @GeneratedValue
     private Long cid;

     @NotEmpty
     @Length(max = 255)
     private String cname;

     @NotEmpty
     @Length(max = 255)
     private String cage;

     private Double cweight;


     public void setCid(Long cid){
         this.cid = cid;
     }

     public Long getCid(){
         return cid;
     }

     public void setCname(String cname){
         this.cname = cname;
     }

     public String getCname(){
         return cname;
     }

     public void setCage(String cage){
         this.cage = cage;
     }

     public String getCage(){
         return cage;
     }

     public void setCweight(Double cweight){
         this.cweight = cweight;
     }

     public Double getCweight(){
         return cweight;
     }

     }
